### ISSUE TITLE
boost.mutex() gives me error

### ISSUE THREAD

**Issue by nsauwen** [kaneplusplus/synchronicity#9] opened 2018-02-11 16:08 UTC
Hi,
I have installed the latest version of the synchronicity package (v 1.3.0). But I get an error upon running 
x <- boost.mutex()

Error in CreateBoostMutexInfo(sharedName, as.double(timeout)) : 
  STRING_ELT() can only be applied to a 'character vector', not a 'NULL'

The above code is also used in the example for the function. What could be the cause for this, is it a bug?

Best regards,
Nicolas

**Comment by kaneplusplus** [comment] 2018-02-11 20:42
Hi Nicholas. I confirm that I'm seeing the same problem in OS X. I think I can get to this in the next day or so. I'll update the thread when I know more.

**Comment by kaneplusplus** [comment] 2018-02-11 22:26
OK, the issue was caused by a change in how the unique identifiers are generated. I've checked in a new version that is working. Please let me know if you run into any other issues.

**Closed as completed by kaneplusplus** 2018-02-11 22:26 UTC

**Comment by nsauwen** [comment] 2018-02-12 13:42
Thanks for the quick intervention! It works now indeed. One more thing: I am taking over maintenance of the NMF package, which depends on your package. Could you update synchronicity package on CRAN to the latest version? As otherwise the NMF package won't pass the checks on CRAN.

**Comment by kaneplusplus** [comment] 2018-02-12 17:32
Certainly. I'm doing a windows build and reverse dependency check now. Hopefully it will be submitted in the next few hours.

Also, if you have *any* interest in contributing to synchronicity, please let me know. I have very limited bandwidth these days but I want to convert the documentation to `roxygen2` and add regression testing that uses the `future` package. I'm happy to include new authors or contributors.

**Comment by kaneplusplus** [comment] 2018-02-12 19:25
The new version of the package is on CRAN.

**Comment by nsauwen** [comment] 2018-02-13 08:47
Thanks!
